version: "3.9"
services:
  spring-api:
    image: spring-api-image
    container_name: spring-api-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    networks:
      - spring-network
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb+srv://root:root@cluster0.suv1fju.mongodb.net/PlanifyFriends?retryWrites=true&w=majority&appName=Cluster0

networks:
  spring-network:
    driver: bridge
