name: CI/CD Pipeline Docker (Build, Test & Verify)

on:
  push:
    branches: [ "CI-CD", "main" ]
  pull_request:
    branches: [ "CI-CD", "main" ]

env:
  IMAGE_NAME: spring-api-image
  CONTAINER_NAME: spring-api-container

jobs:
  build-test-verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: ./mvnw clean package -DskipTests

      - name: Run tests
        run: ./mvnw test

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME .

      - name: Verify with docker-compose
        run: |
          docker-compose up -d
          sleep 15
          docker ps | grep $CONTAINER_NAME
          curl -v http://localhost:9090/api/eventos || echo "Curl test failed but continuing..."
          docker-compose logs --tail=50 spring-api-image
          docker-compose down